server:
  port: 8081

management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

request:
  correlation:
    header-name: X-B3-TraceId # sets the header name to be used for request identification (X-Request-Id by default)
    client:
      http:
        enabled: true  # enables the RestTemplate header propagation (true by default)
      feign:
        enabled: true # enables the Fegin header propagation (true by default)
        
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
---
spring:
  profiles: 
    active: native
---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
    compression:
      enabled: false
    flush-interval: 1
---
spring:
  application:
    name: demo-service2
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
