server:
  port: 8888

management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///D:/GitProject/spring-cloud-framework/demo-config-file
#          uri: https://github.com/making/config-repo
          #basedir: target/config
          #uri: classpath:*

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: classpath:/
---
spring:
  profiles: 
    active: default
    
---
spring:
  application:
    name: configserver
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
