server:
  port: 8888

management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: configserver
  profiles: 
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoffice/spring-cloud-config

