server:
  port: 8888

management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
---
spring:
  profiles: 
    active: native
    
---
spring:
  application:
    name: configserver
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
