server:
  port: 7979

ribbon:
  eureka:
    enabled: false
    
turbine:
  appConfig: demo-service,demo-service2
  aggregator:
    clusterConfig: DEMO-SERVICE,DEMO-SERVICE2
 
management:
  context-path: /

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
    
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
---
spring:
  profiles: 
    active: native
    
---
spring:
  application:
    name: hystrix
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
