server:
  port: 8090

management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health


spring:
  sleuth:
    feign:
      enabled: true
---
feign:
  hystrix:
    enabled: true

security:
  user:
    name: root
    password: 123456
    
spring:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
---
    
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
---
spring:
  profiles: 
    active: native

---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
    compression:
      enabled: false
    flush-interval: 1
---
spring:
  application:
    name: demo-oauth2-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
