server:
  port: 8090

spring:
  application:
    name: demo-oauth2-server
  profiles: 
    active: native
---


management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.security: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health


spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
  sleuth:
    feign:
      enabled: true
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: http://localhost:8090/oauth/token
      userAuthorizationUri: http://localhost:8090/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://localhost:8090/user
      preferTokenInfo: false
#  zipkin:
#    baseUrl: http://localhost:9411
#    enabled: true
#    compression:
#      enabled: false
#    flush-interval: 1
---
#feign:
#  hystrix:
#    enabled: true

#security:
#  user:
#    name: root
#    password: 123456
    
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
