server:
  port: 8080

management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health


spring:
  sleuth:
    feign:
      enabled: true
---
feign:
  hystrix:
    enabled: true
    
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
---
spring:
  profiles: 
    active: native

---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
    compression:
      enabled: false
    flush-interval: 1
---
spring:
  application:
    name: demo-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
