server:
  port: 8082
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  eureka:
    enabled: false
    
#proxy service
zuul:
  routes:
    demo-service:
      path: /d/**
      serviceId: demo-service
#      url: http://localhost:8080
    demo-service2: 
      path: /d2/**
      serviceId: demo-service2
#      url: http://localhost:8081

#Load Balance
demo-service:
  ribbon:
    listOfServers: localhost:8080

demo-service2:
  ribbon:
    listOfServers: localhost:8081
    
turbine: 
   clusterNameExpression: zuul-server

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            
management:
  context-path: /
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          #uri: https://github.com/spring-cloud-samples/config-repo
#          #basedir: target/config
#          uri: classpath:*

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
---
spring:
  profiles: 
    active: native
    
---
spring:
  application:
    name: zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
